package:
  name: arccssive
  version: "0.1.0"

source:
  fn: ARCCSSive-0.1.0.tar.gz
  url: https://files.pythonhosted.org/packages/28/5e/4f1e3cb0dcddb7985da51c845af047d032c9058a6a2c9bcbd586434b45de/ARCCSSive-0.1.0.tar.gz
  md5: 347e8425a4436a0e46496a855ddbc66d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - arccssive = arccssive:main
    #
    # Would create an entry point called arccssive that calls arccssive.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sqlalchemy
    - six

  run:
    - python
    - sqlalchemy
    - six

test:
  # Python imports
  imports:
    - ARCCSSive
    - ARCCSSive.CMIP5

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/coecms/ARCCSSive
  license: Apache 2.0
  summary: 'ARCCSS Data Access Tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
